name: Run Python Linter

on: [ push, pull_request ]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev-2.1.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
      - name: Run Mypy tests
        run: mypy . --ignore-missing-imports
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev-2.1.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8 tests
        run: flake8 . --count --max-line-length=88 --show-source --statistics
