name: Run Python Linter (Branch - dev-2.1.0)

on: [ push, pull_request ]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev-2.1.0
      - name: Get and run Mypy tests
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          mypy . --ignore-missing-imports || exit 0
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev-2.1.0
      - name: Get and run flake8 tests
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          flake8 . --count --max-line-length=88 --show-source --statistics || exit 0
